### PR TITLE
lets call Channel as Shader because it is refering to which shader should be used

### PR DESCRIPTION
**Pull request by CuteWaterBeary**

### CODE REVIEW

**Comment by ReinaS-64892** [comment]
Channel does not refer specifically to which shader to use, but is there to atlas two or more textures from the same range of materials.

This is a temporary workaround so that if you merge materials after atlasing, the number of materials will change and the subsequent "AtlasTexture" will not be able to perform the atlasing because it will refer to the material by its index.

We plan to improve the channel so that it will work correctly regardless of whether materials are merged or not, so we plan to delete the channel itself.

**Comment by ReinaS-64892** [comment]
AtlasTexture is completely per-material selection, but I think it would be nice to have a new atlasing component that selects per shader, so please create that "issue" if necessary.

**Comment by CuteWaterBeary** [comment]
> AtlasTexture is completely per-material selection, but I think it would be nice to have a new atlasing component that selects per shader, so please create that "issue" if necessary.

While trying to learn how to use your tool I've only used this to pick which meshes should use a different shader and the word channel really confuses me as I might not be familiar with the technical definition. I don't think a new feature specifically limiting to just shaders should be created because this seems to do that but I'm still sorta confused as to what it fully does. I will wait until you fully implement your goals with this and maybe it will make more sense then.

**Comment by ReinaS-64892** [comment]
I did not think the naming of "Channel" was correct, but I think it is better to use multiple AtlasTextures than this kind of functionality,
I implemented it as a temporary measure without much thought... Sorry for any confusion it may have caused.

**Comment by CuteWaterBeary** [comment]
No worries. I think you are making a wonderful tool!

**Pull request closed without merging**
